"""
app.execution.contracts
-----------------------
Data structures describing code generation and sandboxed execution.

Responsibility:
  Record what code was generated for an analysis, and what the
  sandboxed execution of that code produced.

Design rules (PROOFLENS_MASTER_CONTEXT.md §10, §11):
  - The result value in ExecutionResult comes EXCLUSIVELY from stdout
    of the sandboxed process.  It is NEVER copied from LLM output.
  - Generated code must use real column names and contain assertions.
  - The code file path is stored so it can be hashed and replayed.

Core principle:
  CODE COMPUTES — the execution result is the authoritative number.
  (PROOFLENS_MASTER_CONTEXT.md §2, §11)
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field


class GeneratedCode(BaseModel):
    """
    Metadata about the analysis code generated by the Qwen planner.

    The code itself is written to a file (code_path).  This contract
    records provenance — it does NOT contain the code inline to avoid
    issues with very large generated scripts.
    """

    code_path: Path = Field(
        ...,
        description=(
            "Path to the generated Python analysis file "
            "(e.g. proofs/<session_id>/analysis.py)."
        ),
    )
    code_sha256: str | None = Field(
        default=None,
        description=(
            "SHA-256 hash of the code file content. "
            "Used for reproducibility checks. "
            "(PROOFLENS_MASTER_CONTEXT.md §23)"
        ),
    )
    world_id: str = Field(
        ...,
        description=(
            "The RepairWorld this code was generated for. "
            "The SAME code_path is reused across all worlds — only the "
            "data_path argument changes per execution."
        ),
    )
    policy_sha256: str | None = Field(
        default=None,
        description=(
            "SHA-256 hash of the serialised RepairPolicy list used to produce the world. "
            "(PROOFLENS_MASTER_CONTEXT.md §23)"
        ),
    )
    code_content: str | None = Field(
        default=None,
        description="Inline generated Python code string.",
    )


class ExecutionResult(BaseModel):
    """
    The output of one sandboxed execution of the analysis code
    against one RepairWorld.

    Pipeline position: SANDBOXED EXECUTION → ACTUAL RESULT FROM CODE
    (stages 9–10 of 18).

    CRITICAL:
      result_value is parsed from stdout of the subprocess.
      It must NEVER be set from LLM text or hardcoded.
      If execution fails, result_value is None and execution_success is False.
    """

    world_id: str = Field(
        ...,
        description="The RepairWorld this execution corresponds to.",
    )
    code_path: Path = Field(
        ...,
        description="Path to the analysis script that was executed.",
    )
    stdout: str = Field(
        default="",
        description="Complete standard output captured from the subprocess.",
    )
    stderr: str = Field(
        default="",
        description="Complete standard error captured from the subprocess.",
    )
    exit_code: int = Field(
        ...,
        description="Process exit code (0 = success, non-zero = failure).",
    )
    execution_success: bool = Field(
        ...,
        description=(
            "True only if exit_code == 0 and stdout contained a parseable result. "
            "Set deterministically by the executor — not by the LLM."
        ),
    )
    result_value: Any = Field(
        default=None,
        description=(
            "The primary numerical (or string/list/dict) result produced by execution. "
            "This is the authoritative computed value for this world. "
            "None if execution failed or result was not emitted."
        ),
    )
    result_type: str | None = Field(
        default=None,
        description="Type of the result: 'float', 'int', 'str', 'bool', 'dict', 'list', etc.",
    )
    execution_error: str | None = Field(
        default=None,
        description=(
            "Human-readable description of the execution failure, "
            "if execution_success is False."
        ),
    )
    error_type: str | None = Field(
        default=None,
        description="Class/type of the execution error (e.g. 'MissingTableError', 'TimeoutError', 'UnsafeCodeError').",
    )
    duration_seconds: float | None = Field(
        default=None,
        description="Wall-clock time the subprocess took to complete.",
    )
    execution_time_ms: float | None = Field(
        default=None,
        description="Execution time in milliseconds.",
    )
    table_names: list[str] = Field(
        default_factory=list,
        description="Tables supplied to this execution.",
    )
    row_counts: dict[str, int] = Field(
        default_factory=dict,
        description="Row counts of the input tables.",
    )
    generated_code_hash: str | None = Field(
        default=None,
        description="SHA-256 hash of the executed analysis code.",
    )
    input_data_hashes: dict[str, str] = Field(
        default_factory=dict,
        description="SHA-256 hashes of the supplied input tables.",
    )
    output_truncated: bool = Field(
        default=False,
        description="True if stdout or stderr exceeded maximum output size limit.",
    )
    row_count_waterfall: dict[str, int] = Field(
        default_factory=dict,
        description=(
            "Row counts at each transformation step, emitted by the analysis script. "
            "Example: {'input': 10000, 'after_dedup': 9880, 'after_date_filter': 7000}. "
            "Values come from actual execution output — never from LLM text. "
            "(PROOFLENS_MASTER_CONTEXT.md §21)"
        ),
    )
